### ISSUE TITLE
Tool-AI link content - no longer hosted by original host

### ISSUE THREAD

**Issue by koenrane** [gwern/gwern.net#1]
Gwern,

While reading the post [Why Tool AIs Want to be Agent AIs](https://www.gwern.net/Tool-AI), I noticed that the original host (Yahoo Groups) for a discussion is no longer hosted as of December 14, 2019.

Here is the link in the article:

[...coined by Holden Karnofsky in a July 2011 discussion](https://www.gwern.net/docs/www/groups.yahoo.com/924435c853aefdb830b225dab54fb9588c2f34e3.html)

![image](https://user-images.githubusercontent.com/80125299/111661546-1bde2e80-87dd-11eb-91aa-8db888a4fc74.png)

**Comment by gwern** [comment]
Tricky. None of the archived copies of the Groups discussion (like my local copy, IA, or [Jeff](https://www.jefftk.com/givewell-archive/archive-2011)) appears to be at all high-quality or to incorporate the specific term, suggesting they're missing parts. I assume that I did check back then because I usually check things like that, but there's no point in providing a link if it's missing the reason it's being linked... The meat of it seems to be Karnofsky's debate with Tallinn, but that's long since gone too; fortunately, that one can be fished out of the IA: https://www.gwern.net/docs/xrisks/2011-05-10-givewell-holdenkarnofskyjaantallinn.doc

---

If you have further small bug fixes, it'd probably be better to email me directly. Github issues are a heavyweight process for such things. Or at least put them all in one issue to be more easily dealt with.

**Comment by koenrane** [comment]
Definitely tricky. After reading the some of the discussion, it's possible that there are missing some parts. Doc from the IA, when searched, shows 5 results for "tool", with no results for "tool mode"/"tool AGI". I did find something close to the latter term as "would-be-AGI as a tool".
Informative read. So, thanks for that link.

I appreciate the response. In the future, I will be more thorough in my digging before creating an issue. Also, if pointing out these minor issues are not helpful regarding time allocation, let me know. I read a lot on your site, and usually like to note issues that I run into while reading.
If you prefer email, I will use that mode of communication. I share your sentiment regarding GH for very minor issues.

KR

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
