### ISSUE TITLE
could u pls write a readme of how to build your blog?

### ISSUE THREAD

**Issue by luckypoem** [gwern/gwern.net#10]
hi.
could u pls write a readme of how to build your blog?

thank you!

**Comment by gwern** [comment]
Have you read the comments in `hakyll.hs`?

**Comment by luckypoem** [comment]
HI.

root@AR:/usr/local/gwern.net/gwern.net-master# ghc -rtsopts -threaded -O2 -fforce-recomp -optl-s --make hakyll.hs
[1 of 2] Compiling Feed             ( Feed.hs, Feed.o )

Feed.hs:30:1: error:
    Failed to load interface for ‘Data.FileStore.Types’
    Use -v to see a list of the files searched for.

Feed.hs:32:1: error:
    Failed to load interface for ‘Text.Atom.Feed’
    Use -v to see a list of the files searched for.

Feed.hs:35:1: error:
    Failed to load interface for ‘Text.Atom.Feed.Export’
    Use -v to see a list of the files searched for.
root@AR:/usr/local/gwern.net/gwern.net-master#

i installed those dependencies.how to fix the errors above?
tks

**Comment by gwern** [comment]
I don't know then. If you cabal installed `filestore` and `feed`, it should just work. You apparently have Haskell problems in general.

**Comment by luckypoem** [comment]
i see:
cabal install filestore
cabal install feed

then i ran "ghc --make hakyll.hs",it generated exec file:hakyll.
"./hakyll build" generated the _site dir.
but after i created a new source post,and publish it ,why the new published post don't appear in the homepage?

thank you

**Comment by gwern** [comment]
The hompage is `index`. The index is hand-written; I never created an auto-populating homepage because I wanted only finished stuff I had selected for the homepage, and to put them in loose order of quality. So new files do not automatically show up - gwern.net is not a blog, as I keep telling people - and that's not a surprise. If you want something like that, you can look through the various Hakyll tutorials & Hakyll blogs and see how they use templates to do that.

**Comment by gwern** [comment]
Is the hakyll.hs documentation adequate and this issue can be closed?
