### ISSUE TITLE
Evernote is no longer public, but there is still a link to it

### ISSUE THREAD

**Issue by gustavAR** [gwern/gwern.net#17]
The Evernote notebook linked to from https://www.gwern.net/Statistical-notes is no longer public.

I mostly created this issue in order to have the decision to hide the notebook be officially confirmed, since it isn't referenced on the website.

**Comment by gwern** [comment]
Yes, it's deliberate (I didn't realize there was a link in that page though). To copy over one email I wrote:

> I did take it down deliberately, yes. I had a few reasons and had been
> thinking about it for a while. One thing was that I didn't like the
> slight worry I felt: 'what would other people think about me picking
> this clipping? Would it be misinterpreted as an endorsement?' Another
> thing was that it didn't seem like it was of much value to anyone
> else, as you are one of the only people to mention using it over the
> past 6 years or so. Much of it is simply that I am increasingly
> unhappy with Evernotes in general. Their clipping quota seems smaller
> ever month, they charge an excessive amount (and their UI still nags
> you even when you are paying!), and their Firefox plugin (about the
> only way I use Evernotes) has for years continuously suffered this
> terrible performance degradation where it slows down with each clip,
> especially screenshots (which somehow manage to cause Firefox to
> consume >16GB RAM and works only because my laptop has 32GB), to the
> point where after a few days I can take a coffee break before it
> finishes clipping a note and I need to restart Firefox just to make it
> usable again. I have been considering switching to some other
> scrapbooking app, like maybe Scrapbook X, but even there I have
> problems: Firefox is killing the entire extension ecosystem with its
> 'Quantum' version and who knows what will be the best extension then?
> Or if it'll interoperate with my Nixnotes backup. Ugh. In any case,
> removing the public feed is one step in leaving Evernotes.

I am currently trying out limited access to my evernotes as a [Patreon](https://www.patreon.com/gwern) reward, since you can share notebooks with specific email accounts. So far no one I've given access to has reported any fatal problems with this as a method of sharing, so I may make it official at the end of the month. If you're a patron, or would just rather like access, send me an email address and I'll add it now.

**Comment by gustavAR** [comment]
That seems reasonable.
