### ISSUE TITLE
Multiple Issues with Rendering on Safari iPadOS

### ISSUE THREAD

**Issue by SolAstrius** [gwern/gwern.net#4]
I use iPadOS 14.7.1.

Page I’ve encountered issues with: https://gwern.net/Lunar-sleep

## Drop Cap
![CB27DB76-1F74-48CA-AF6F-0C11713199C3](https://user-images.githubusercontent.com/70720738/164080083-23b64143-82c5-43d0-b6ff-a56e86517ad9.png)

## Right Options Menu partially covers content
And doesn’t always work.
![CCAFE51E-DB31-40E3-AAF2-ACA1E8148729](https://user-images.githubusercontent.com/70720738/164080093-964f68c3-4df0-4806-a241-25bb2376da6c.png)

## A content Text is outside the box it is intended to be in
![7511FB73-CED8-4C9F-9BE0-2CDDD7039832](https://user-images.githubusercontent.com/70720738/164080099-478cf8e3-898f-4bf4-aaa9-8cd34e2f6d3f.png)

## Navigation is not centered
I’m not sure it’s a bug though, is it intended this way?

![C42CA4EE-EA46-4A07-AB3D-60A3FF1619AA](https://user-images.githubusercontent.com/70720738/164080107-b0755252-9f3b-4ddc-86c6-d9eb72e0b9ad.png)

**Comment by gwern** [comment]
The dropcap looks like a bug (needs more bottom margin, perhaps?).

The theme toggle should've faded out before the two figures, so there may be a bug there. (It should have definitely faded out by the end of the page!) Tables are kinda weird, so wouldn't be surprising if a media-query or something is wrong.

Putting full-width stuff in blockquotes doesn't look great regardless so I'll simply remove the blockquotes.

By navigation not being centered, are you referring to the Disqus stuff? On a tablet, the body isn't going to have identical margins because of the sidebar at the left.

**Comment by SolAstrius** [comment]
> By navigation not being centered, are you referring to the Disqus stuff? On a tablet, the body isn't going to have identical margins because of the sidebar at the left.

Yes, Disqus is (maybe?) too wide compared to the content. If I'm being honest, this sidebar asymmetry just doesn't seem right to me for some strange reason. I'm not sure if there is a better way to do it, though.

**Comment by gwern** [comment]
Disqus is hard to style because it is a mess of dynamic JS and CSS they inject and run themselves. I don't know if we even *can* style it, or if we could, that it would *stay* styled... This is one of the reasons I've been gradually shifting over the years to thinking that I will just remove Disqus entirely.

The sidebar asymmetry doesn't bother me too much because it still feels like a book: you're reading the left page of a book. On the other hand, that may be precisely the issue (book conventions rather than Internet conventions - similar to how people dislike justified text or indented paragraphs rather than newlines);  it's not like we're putting sidenotes into the margin; and maybe we should switch to mobile mode earlier than we do in terms of width, which would center it.

**Comment by SolAstrius** [comment]
The theme toggle fadeout seems to be fixed. 

But now it’s impossible to open any links; they open only through the “Open in new tab” context menu.

**Comment by SolAstrius** [comment]
Also, it seems that the site’s navigation (the left sidebar) is now missing altogether, there is neither the compact mobile version nor the desktop one.

![243ABC22-7F0E-44D0-91F9-839F89F9A750](https://user-images.githubusercontent.com/70720738/164758861-38dd0a8c-33ce-448c-b569-85ecb1a4a2ea.png)

**Comment by gwern** [comment]
You've enabled reader-mode by default (note the darkened book in the toggle), so the sidebar & links are hidden.

**Comment by SolAstrius** [comment]
> You've enabled reader-mode by default (note the darkened book in the toggle), so the sidebar & links are hidden.

Oh, my bad, it does work, nvm then.

**Comment by gwern** [comment]
The dropcaps should be fixed now. I think that's everything, are any of the bugs here still active?

**Comment by SolAstrius** [comment]
Let me check on the iPad, I'll reply in a few hours

**Comment by SolAstrius** [comment]
seems right now, closing the issue.
